language: python
cache: pip
python:
- '2.7'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install
- pip install tox-travis
script:
- poetry run tox
