site_name: {{ cookiecutter.project_name }}

nav:
- Home: 'index.md'
- Development Guide:
    - 'contributing.md'
    - 'tasks.md'
    - 'coverage.md'
- About:
    - 'authors.md'
    - 'license.md'
    - 'changelog.md'

markdown_extensions:
    - markdown_include.include:
        base_path: docs
