[tool.poetry]
name = "snek-template"
version = "0.1.0"
description = "Another cookicutter template for general Python projects"
authors = ["Javier Sanchez Portero <javiersanp@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4 || ~2.7"

[tool.poetry.dev-dependencies]
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
