# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    matrix:
      - image: circleci/python:3.7
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install poetry
          command:
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

      - run:
          name: Create virtual env and install dependencies
          command: |
            export PATH="$HOME/.poetry/bin:$PATH"
            poetry config settings.virtualenvs.in-project true
            poetry install
      - run:
          name: Run linter and tests
          command: |
            export PATH="$HOME/.poetry/bin:$PATH"
            pyenv local 3.7.2 3.6.7
            poetry run tox
